# Generated by Django 2.2.19 on 2022-07-06 12:36

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='debit',
            new_name='bank',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_profile',
                #to='users.UserProxy',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
