# Generated by Django 2.2.19 on 2022-07-07 05:14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_profile',
                #to='users.UserProxy',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
