# Generated by Django 2.2.19 on 2022-06-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20220622_0952'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='not empty players list',
        ),
    ]
