# Generated by Django 2.2.19 on 2022-08-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20220707_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='info',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='step',
        ),
        migrations.AddField(
            model_name='game',
            name='action_name',
            field=models.CharField(default='setup', max_length=30),
        ),
        # migrations.AlterField(
        #     model_name='player',
        #     name='user',
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name='_players',
        #         to='users.UserProxy',
        #     ),
        # ),
    ]
