# Generated by Django 2.2.19 on 2022-08-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20220809_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='beds_storage',
        ),
        migrations.AddField(
            model_name='game',
            name='bank',
            field=models.PositiveIntegerField(default=0, verbose_name='sum of all beds has maded for game round'),
        ),
        # migrations.AlterField(
        #     model_name='player',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_players', to='users.UserProxy'),
        # ),
    ]
