# Generated by Django 2.2.19 on 2022-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20220810_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='player`s number in a circle starting from 0'),
        ),
    ]
