# Generated by Django 4.1 on 2022-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_alter_player_user_game_only one host at game'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='only one host at game',
        ),
    ]
