# Generated by Django 4.1 on 2022-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_remove_playerbet_value_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbet',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
