# Generated by Django 4.1 on 2022-08-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_playerbet_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbet',
            old_name='_values',
            new_name='values',
        ),
    ]
