# Generated by Django 4.1 on 2022-08-23 12:21

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_player_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='passed',
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(
                default=True, verbose_name='player did not say "pass" yet'
            ),
        ),
        migrations.AlterField(
            model_name='playerbet',
            name='values',
            field=models.JSONField(
                blank=True,
                # default=games.models.player.get_bet_default,
                validators=[
                    # games.models.player.type_is_list_int,
                    # games.models.player.bet_multiplicity,
                ],
            ),
        ),
    ]
