# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_remove_player_passed_player_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='performer',
        ),
    ]
