# Generated by Django 4.1 on 2022-08-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_alter_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='host',
            new_name='is_host',
        ),
    ]
