# Generated by Django 4.1 on 2022-08-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_alter_playerbet_managers_remove_playerbet_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbet',
            name='player',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bets',
                to='games.player',
            ),
        ),
    ]
