# Generated by Django 4.1 on 2022-09-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_alter_game_bank_alter_player_is_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='players_manager',
                to='games.game',
            ),
        ),
    ]
