# Generated by Django 4.1 on 2022-10-05 05:14

import core.models
from django.db import migrations, models
import games.models.fields
import games.models.game
from django.db.models.fields import NOT_PROVIDED

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_game_actions_history_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rounds_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='actions_history',
            field=models.JSONField(blank=True, default=core.models.get_list_default),
        ),
        migrations.AlterField(
            model_name='game',
            name='bank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=games.models.fields.CardListField(
                auto_created=None,
                blank=True,
                db_index=None,
                default=NOT_PROVIDED,
                editable=None,
                help_text=None,
                serialize=None,
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_generator',
            field=models.CharField(
                default=games.models.game.get_deck_default, max_length=79
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=games.models.fields.CardListField(
                auto_created=None,
                blank=True,
                db_index=None,
                default=NOT_PROVIDED,
                editable=None,
                help_text=None,
                serialize=None,
            ),
        ),
    ]
