# Generated by Django 4.1 on 2022-10-07 07:24

import core.models
import core.validators
from django.db import migrations, models
import games.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_game_rounds_counter_alter_game_actions_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bets',
            field=models.JSONField(
                default=core.models.get_list_default,
                validators=[core.validators.bet_multiplicity_list],
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=games.models.fields.CardListField(
                blank=True, default=games.models.fields.cardlist_default
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds_counter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=games.models.fields.CardListField(
                blank=True, default=games.models.fields.cardlist_default
            ),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=games.models.fields.CardListField(
                blank=True, default=games.models.fields.cardlist_default
            ),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='not passed player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='PlayerBet',
        ),
    ]
