# Generated by Django 4.1 on 2022-10-07 12:05

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0051_player_bets_alter_game_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bets',
            field=models.JSONField(
                blank=True,
                default=core.models.get_list_default,
                validators=[
                    # core.validators.bet_multiplicity_list
                ],
            ),
        ),
    ]
