# Generated by Django 4.1 on 2022-10-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_bank'),
        ('games', '0054_remove_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPreform',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players_preforms',
                        to='games.game',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players_preforms',
                        to='users.userproxy',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user waiting to participate',
                'verbose_name_plural': 'users waiting to participate',
            },
        ),
        migrations.AddConstraint(
            model_name='playerpreform',
            constraint=models.UniqueConstraint(
                fields=('user', 'game'),
                name='unique: User could not make many request to join a sigle game. ',
            ),
        ),
    ]
