# Generated by Django 4.1 on 2022-10-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0055_playerpreform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='config_name',
            field=models.CharField(
                choices=[
                    ('bizarre', 'Bizarre'),
                    ('cheeky', 'Cheeky'),
                    ('foolish', 'Foolish'),
                    ('classic', 'Classic'),
                ],
                default='classic',
                max_length=30,
            ),
        ),
    ]
