# Generated by Django 2.2.19 on 2022-06-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from games.models import CardListField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deck', CardListField(verbose_name='deck of cards')),
                ('table', CardListField(verbose_name='cards on the table')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('hand', CardListField(verbose_name='cards in players hand')),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to='games.Game',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
