# Generated by Django 2.2.19 on 2022-06-19 14:01

from django.db import migrations
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=games.models.CardListField(blank=True, verbose_name='deck of cards'),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=games.models.CardListField(blank=True, verbose_name='cards on the table'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=games.models.CardListField(blank=True, verbose_name='cards in players hand'),
        ),
    ]
