# Generated by Django 2.2.19 on 2022-06-22 09:20

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220619_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'poker game', 'verbose_name_plural': 'poker games'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'user in game', 'verbose_name_plural': 'users in games'},
        ),
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=games.models.CardListField(default=[], verbose_name='deck of cards'),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=games.models.CardListField(default=[], verbose_name='cards on the table'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique'),
        ),
    ]
