# Generated by Django 2.2.19 on 2022-06-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20220626_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprocess',
            name='info',
            field=models.CharField(default='not define yet', max_length=200),
        ),
    ]
