# Generated by Django 2.2.19 on 2022-06-26 14:42

from django.db import migrations, models
import django.db.models.deletion
import games.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gameprocess_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', games.fields.StacksField(null=True)),
                ('suit', games.fields.StacksField(null=True)),
                ('row', games.fields.StacksField(null=True)),
                ('highest_card', games.fields.StacksField(null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combo', to='games.Player')),
            ],
        ),
    ]
