# Generated by Django 2.2.19 on 2022-06-27 06:51

from django.db import migrations, models

import games.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_playercombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=games.fields.CardListField(
                auto_created=None,
                blank=True,
                db_index=None,
                editable=None,
                help_text=None,
                serialize=None,
                verbose_name='deck of cards',
            ),
        ),
        migrations.AlterField(
            model_name='game',
            name='table',
            field=games.fields.CardListField(
                auto_created=None,
                blank=True,
                db_index=None,
                editable=None,
                help_text=None,
                serialize=None,
                verbose_name='cards on the table',
            ),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='highest_card',
            field=games.fields.StacksField(default=[]),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='rank',
            field=games.fields.StacksField(default=[]),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='row',
            field=games.fields.StacksField(default=[]),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='suit',
            field=games.fields.StacksField(default=[]),
        ),
    ]
