# Generated by Django 2.2.19 on 2022-06-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20220627_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercombo',
            name='player',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_combo',
                to='games.Player',
            ),
        ),
    ]
