# Generated by Django 2.2.19 on 2022-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_playercombo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprocess',
            name='game',
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='unique',
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.CharField(default='not define yet', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='not define yet', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='step',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playercombo',
            name='name',
            field=models.CharField(default='<not tracked yet>', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(
                fields=('user', 'game'), name='User can play in Game only by one Player'
            ),
        ),
        migrations.DeleteModel(
            name='GameProcess',
        ),
    ]
