# Generated by Django 2.2.19 on 2022-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20220629_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck_generator',
            field=models.CharField(
                default='Decks.standart_52_card_deck_plus_jokers',
                max_length=79,
                verbose_name='name of deck generator method or contaianer',
            ),
        ),
    ]
