# Generated by Django 2.2.19 on 2022-07-06 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20220706_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='beds_storage',
            field=models.PositiveIntegerField(default=0, verbose_name='sum of all beds maded for game round'),
        ),
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='creation data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modification data'),
        ),
        migrations.AddField(
            model_name='player',
            name='bet',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='creation data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='dealer',
            field=models.BooleanField(default=False, verbose_name='dealer botton'),
        ),
        migrations.AddField(
            model_name='player',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modification data'),
        ),
    ]
