# Generated by Django 2.2.19 on 2022-07-07 05:14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20220707_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_players',
                #to='users.UserProxy',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
