# Generated by Django 2.2.19 on 2022-07-07 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20220707_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_players',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
