# Generated by Django 2.2.19 on 2022-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['position'], 'verbose_name': 'user in game (player)', 'verbose_name_plural': 'users in games (players)'},
        ),
        migrations.AddField(
            model_name='player',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='player said "pass"'),
        ),
    ]
