# Generated by Django 2.2.19 on 2022-08-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20220811_0716'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='player',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_players', to='users.UserProxy'),
        # ),
        migrations.AlterField(
            model_name='playerbet',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
