# Generated by Django 4.1 on 2022-08-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220707_0632'),
        ('games', '0030_auto_20220811_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_players',
                to='users.userproxy',
            ),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(
                check=models.Q(('bank', 1), _negated=True),
                name='only one host at game',
            ),
        ),
    ]
