# Generated by Django 4.1 on 2022-08-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_rename__values_playerbet_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbet',
            name='value',
        ),
    ]
