# Generated by Django 4.1 on 2022-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_remove_playerbet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='performer',
            field=models.BooleanField(
                default=False, verbose_name='game waiting for his action'
            ),
        ),
    ]
