# Generated by Django 4.1 on 2022-09-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_alter_playerbet_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bank',
            field=models.PositiveIntegerField(
                default=0, verbose_name='all accepted beds for game round'
            ),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(verbose_name='game host'),
        ),
        migrations.DeleteModel(
            name='PlayerCombo',
        ),
    ]
