# Generated by Django 4.1 on 2022-09-25 10:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='actions_history',
            field=models.JSONField(default=core.models.get_list_default),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
